language: java
script: "./gradlew build"
cache:
  directories:
  - "$HOME/.gradle"
notifications:
  slack:
    rooms:
      secure: gCDfp8nV9kwuZp3h+exLyzD+HHXZucVK9zNi2oCtIvFymTeFjuBVJ4wOBmBDTB0jXXEsBAE/JZCHktnzUGDbcHbColUow7qEJYWRhadljwYJNLMo39FGR4+y30VCr7JPHUXt+9WLnGe8zDDCBVPipQJ/L6+86MbEfT5Q5dT91eAazXQCa9j9AoLcsf5VJZqlI9CyDyloFocDc0rW2XRu64eByymkYKPOBvnSZ0ba/B4yTyAO5QpQt0IMGBQGgGd0+rRVZU4A7/PQKBqw2c9cCo/76t2lcqhSMafEwWd5fO7PcxR0Peb3kCHri764PySKoucD/SKGOjQgf7iECkRt7gKbvBZU4oaravAsfNIK/olNwKbFa01Vmy/PW4FNaYkqRkAgKgm9PB8oKghycKnESvrlh/6Wz4xOyAqqBCCM1zMyxpueDlugY5XdTI3oRMEZ+x9T9DNjUhXiGcNwrLVCZwoMLlArgPSRZW1igeflFMU82DhhbMj0f0Xt+LjYvAjhsJIvvhPbtWXgOnKRX2oGp9M9yGelAK0vBP+DkNacRsdkAUcKrPVM7zx+UW/q8JxQJhmhMwD0MOgl9oQ4SppNqwv57JhVHtlYOkPqN+sJwcvZQ8otmbV1ZJdQ/jep7liiNV76W6kyE4Uc52vpWU89hsNzJBkdxMQQ01oTBG6Rsjk=
    on_success: change
    on_failure: change
